version: "3"

services:
  database:
    image: mysql:8.0.30
    restart: always
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
      - MYSQL_USER=${MYSQL_USER_NAME}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-net
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/${MYSQL_DATABASE_NAME}?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER_NAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_USER_PASSWORD}
    networks:
      - springboot-mysql-net
networks:
  springboot-mysql-net:
    driver: bridge

