debug: false
logging:
  level:
    me.honki12345.wantedassignment: debug
    org.springframework.web.server: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.orm.jdbc.bind: trace
spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always

me.honki12345.jwt.header: Authorization
    #HS512 알고리즘
    #echo 'wanted-assignment-wanted-assignment-wanted-assignment-wanted-assignment-wanted-assignment' | base64
me.honki12345.jwt.secret: d2FudGVkLWFzc2lnbm1lbnQtd2FudGVkLWFzc2lnbm1lbnQtd2FudGVkLWFzc2lnbm1lbnQtd2FudGVkLWFzc2lnbm1lbnQtd2FudGVkLWFzc2lnbm1lbnQK
me.honki12345.jwt.token-validity-in-seconds: 86400 * 10

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect